### ISSUE TITLE
getPropositions & updatePropositions Error Handling

### ISSUE THREAD

**Issue by thebaldarchitect** [adobe/aepsdk-optimize-android#61]
### Expected Behaviour
Android getPropositions api's does not have error handling. Nor does updatePropositions.

### Actual Behaviour
Android getProp function does not have error handling like iOS.

### Reproduce Scenario (including but not limited to)
You can see it in the definition and documentation.

#### Platform and Version
Latest

**Comment by spoorthipujariadobe** [comment]
Hi @thebaldarchitect,
The AEP Optimize SDK for Android does have error handling for `getPropositions` and `onPropositionsUpdate` APIs. You would need to pass `AdobeCallbackWithError` in the method calls which has `fail(final AdobeError adobeError)` which will be called in case of errors. The `updatePropositions` API by design does not have error handling both on iOS and Android.

Please see examples in the documentation links for more details
https://developer.adobe.com/client-sdks/documentation/adobe-journey-optimizer-decisioning/api-reference/#getpropositions
https://developer.adobe.com/client-sdks/documentation/adobe-journey-optimizer-decisioning/api-reference/#onpropositionsupdate
